# Generated by Django 3.2.8 on 2021-10-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABCCompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
