# Generated by Django 3.2.8 on 2021-10-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABCCompany', '0003_alter_userregistration_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('FeMale', 'FeMale'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
